package com.example

import android.app.Application
import android.content.ClipDescription
import android.content.ClipboardManager
import android.content.Context
import android.os.Build
import android.widget.Toast
import com.example.data.local.AppDatabase
import com.example.data.pref.PreferencesManager
import com.example.data.repository.ClipboardRepository
import com.example.data.repository.QueueRepository
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class SmartClipboardApp : Application() {

    val appScope = CoroutineScope(SupervisorJob() + Dispatchers.Default)

    val database by lazy { AppDatabase.getInstance(this) }
    val repository by lazy { ClipboardRepository(database.clipboardDao()) }
    val preferences by lazy { PreferencesManager.getInstance(this) }
    val queueRepository by lazy { QueueRepository(database.queueDao(), this, preferences) }

    private var clipboardListener: ClipboardManager.OnPrimaryClipChangedListener? = null
    @Volatile
    private var lastProcessedClipText: String? = null

    override fun onCreate() {
        super.onCreate()
        instance = this

        // 1. Initial cleanup of expired items on startup
        appScope.launch {
            repository.cleanupExpired()
            queueRepository.cleanupExpired()
            if (preferences.queueModeEnabled.value) {
                queueRepository.syncSystemClipboardWithNext()
            }
        }

        // 2. Setup periodic lightweight cleanup (every 30 seconds)
        appScope.launch {
            while (isActive) {
                delay(30_000L)
                repository.cleanupExpired()
                queueRepository.cleanupExpired()
            }
        }

        // 3. Monitor system clipboard while application process has focus
        setupClipboardMonitor()
    }

    private fun setupClipboardMonitor() {
        val clipboardManager = getSystemService(Context.CLIPBOARD_SERVICE) as? ClipboardManager ?: return

        clipboardListener = ClipboardManager.OnPrimaryClipChangedListener {
            appScope.launch {
                capturePrimaryClip(clipboardManager)
            }
        }
        clipboardManager.addPrimaryClipChangedListener(clipboardListener)
    }

    suspend fun capturePrimaryClip(clipboardManager: ClipboardManager? = null) {
        val cm = clipboardManager ?: getSystemService(Context.CLIPBOARD_SERVICE) as? ClipboardManager ?: return
        if (!preferences.historyEnabled.value) return

        try {
            val clipData = cm.primaryClip ?: return
            if (clipData.itemCount <= 0) return

            // Sensitive data check (Android 13+ / API 33+)
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                val description = clipData.description
                if (description != null && description.extras != null) {
                    if (description.extras.getBoolean(ClipDescription.EXTRA_IS_SENSITIVE, false)) {
                        // Do not record sensitive clips (passwords, OTPs, etc.)
                        return
                    }
                }
            }

            val item = clipData.getItemAt(0)
            val text = item.coerceToText(this)?.toString()?.trim()

            if (!text.isNullOrEmpty()) {
                com.example.util.DebugLog.d("CAPTURE-CLIP", "text='$text'")
                if (text == lastProcessedClipText) {
                    return
                }
                // If this clipboard event was generated by our own Queue sync, ignore it
                if (queueRepository.isSuppressedClip(text)) {
                    com.example.util.DebugLog.d("CAPTURE-SUPPRESSED", "text='$text'")
                    lastProcessedClipText = text
                    return
                }
                lastProcessedClipText = text

                // Append directly to the end of FIFO Queue (no history storage)
                if (preferences.queueModeEnabled.value) {
                    val qId = queueRepository.enqueue(text = text)
                    if (qId > 0) {
                        try {
                            withContext(Dispatchers.Main) {
                                Toast.makeText(this@SmartClipboardApp, "📥 Đã thêm vào hàng đợi: $text", Toast.LENGTH_SHORT).show()
                            }
                        } catch (_: Exception) {}
                    }
                }
            }
        } catch (_: SecurityException) {
            // Android 10+ background restriction when app is not focused/IME
        } catch (_: Exception) {
            // Safe handling
        }
    }

    companion object {
        lateinit var instance: SmartClipboardApp
            private set
    }
}
