package com.example

import android.app.Application
import android.content.ClipDescription
import android.content.ClipboardManager
import android.content.Context
import android.os.Build
import com.example.data.local.AppDatabase
import com.example.data.pref.PreferencesManager
import com.example.data.repository.ClipboardRepository
import com.example.data.repository.QueueRepository
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch

class SmartClipboardApp : Application() {

    val appScope = CoroutineScope(SupervisorJob() + Dispatchers.Default)

    val database by lazy { AppDatabase.getInstance(this) }
    val repository by lazy { ClipboardRepository(database.clipboardDao()) }
    val preferences by lazy { PreferencesManager.getInstance(this) }
    val queueRepository by lazy { QueueRepository(database.queueDao(), this, preferences) }

    private var clipboardListener: ClipboardManager.OnPrimaryClipChangedListener? = null

    override fun onCreate() {
        super.onCreate()
        instance = this

        // 1. Initial cleanup of expired items on startup
        appScope.launch {
            repository.cleanupExpired()
            queueRepository.cleanupExpired()
            if (preferences.queueModeEnabled.value) {
                queueRepository.syncSystemClipboardWithNext()
            }
        }

        // 2. Setup periodic lightweight cleanup (every 30 seconds)
        appScope.launch {
            while (isActive) {
                delay(30_000L)
                repository.cleanupExpired()
                queueRepository.cleanupExpired()
            }
        }

        // 3. Monitor system clipboard while application process has focus
        setupClipboardMonitor()
    }

    private fun setupClipboardMonitor() {
        val clipboardManager = getSystemService(Context.CLIPBOARD_SERVICE) as? ClipboardManager ?: return

        clipboardListener = ClipboardManager.OnPrimaryClipChangedListener {
            appScope.launch {
                capturePrimaryClip(clipboardManager)
            }
        }
        clipboardManager.addPrimaryClipChangedListener(clipboardListener)
    }

    suspend fun capturePrimaryClip(clipboardManager: ClipboardManager? = null) {
        val cm = clipboardManager ?: getSystemService(Context.CLIPBOARD_SERVICE) as? ClipboardManager ?: return
        if (!preferences.historyEnabled.value) return

        try {
            val clipData = cm.primaryClip ?: return
            if (clipData.itemCount <= 0) return

            // Sensitive data check (Android 13+ / API 33+)
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                val description = clipData.description
                if (description != null && description.extras != null) {
                    if (description.extras.getBoolean(ClipDescription.EXTRA_IS_SENSITIVE, false)) {
                        // Do not record sensitive clips (passwords, OTPs, etc.)
                        return
                    }
                }
            }

            val item = clipData.getItemAt(0)
            val text = item.coerceToText(this)?.toString()?.trim()

            if (!text.isNullOrEmpty()) {
                // If this clipboard event was generated by our own Queue sync, ignore it
                if (queueRepository.isSuppressedClip(text)) {
                    queueRepository.clearSuppressedClip()
                    return
                }

                // 1. Always save to regular Clipboard History
                val clipId = repository.saveCopiedText(text)

                // 2. If Queue Mode is ON, append to the end of FIFO Queue
                if (preferences.queueModeEnabled.value) {
                    queueRepository.enqueue(text = text, clipboardId = if (clipId > 0) clipId else null)
                }
            }
        } catch (_: SecurityException) {
            // Android 10+ background restriction when app is not focused/IME
        } catch (_: Exception) {
            // Safe handling
        }
    }

    companion object {
        lateinit var instance: SmartClipboardApp
            private set
    }
}
